# Generated by Django 5.0.1 on 2024-01-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='suspend',
        ),
    ]
