# Generated by Django 5.0.1 on 2024-01-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0003_remove_user_suspend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='employees',
        ),
    ]
