# Generated by Django 5.0.1 on 2024-01-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0004_rename_user_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employees',
            new_name='employee',
        ),
    ]
