# Generated by Django 5.0.1 on 2024-01-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0005_rename_employees_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='EMPLOYEES_DB',
        ),
    ]
