# Generated by Django 5.0.1 on 2024-01-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0006_rename_employee_employees_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees_db',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
