# Generated by Django 5.0.1 on 2024-01-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0007_employees_db_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees_db',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
