# Generated by Django 5.0.1 on 2024-01-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0008_alter_employees_db_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees_db',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
