from django.db import models

# Custom User model to manage user activity

class EMPLOYEES_DB(models.Model): # Autogenerated User ID
    name = models.CharField(max_length=20)
    age = models.IntegerField(default=18)
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    status = models.BooleanField(default=False) # Stores the online status of the user

    def __str__(self):
        return  "Name: " + self.name + " <br> | Age: " + str(self.age) + " | Username: " + self.username + " | Password: " + self.password + " | Status: " + str(self.status)
                    