from django.db import models

# Custom User model to manage user activity

class EMPLOYEES_DB(models.Model): # Autogenerated User ID
    name = models.CharField(max_length=20)                  # Employee name
    age = models.IntegerField(default=18)                   # Employee Age
    username = models.CharField(max_length=20)              # Login Credentials
    password = models.CharField(max_length=20)
    status = models.IntegerField(default=0)                 # Stores the online status of the user
    last_seen = models.DateTimeField(auto_now=True)         # Latest activity timestamp

    def __str__(self):
        return  "Name: " + self.name + " <br> | Age: " + str(self.age) + " | Username: " + self.username + " | Password: " + self.password + " | Status: " + str(self.status) + " Last Seen: " + str(self.last_seen)
                    